---
language: python
cache: pip
python: "2.7"

# Use the new container infrastructure
sudo: false

# Install pip
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible and dependencies
  - pip install ansible ansible-lint

  # Check ansible version
  - ansible --version

  # Install requirements
  - ansible-galaxy install -r tests/requirements.yml -p ./tests/requirements

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=./tests/requirements/:../' >ansible.cfg

script:
  # Run ansible-lint
  - ansible-lint .

  # test singlehost
  - ansible-playbook tests/test-singlehost.yml -i tests/inventory-singlehost

  # test multihost
  - ansible-playbook tests/test-singlehost.yml -i tests/inventory-multihost

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/