- name: "ec2: Initialize default facts"
  set_fact:
    _instance_conga_variant_node_mapping: {}

- name: "ec2: Get ec2 instance facts for current instance"
  ec2_instance_facts:
    filters:
      instance-state-name: running
      ip-address: "{{ inventory_hostname }}"
    region: "{{ conga_host_facts_aws_region }}"
  delegate_to: localhost
  become: no
  register: _ec2_facts_instance

- name: "ec2: instance facts"
  set_fact:
    # convert the ec2 tags into facts (lists)
    _instance_conga_nodes: "{{ _ec2_facts_instance.instances[0].tags.conga_nodes.split(',') }}"
    _instance_conga_variants: "{{ _ec2_facts_instance.instances[0].tags.conga_variants.split(',') }}"
    _instance_conga_variant_node_mapping_list: "{{ _ec2_facts_instance.instances[0].tags.conga_variant_node_mapping.split(',') }}"