- name: "Set host_pattern facts"
  set_fact:
    # get the conga_variants from the host pattern
    _host_pattern_variants: "{{ conga_host_facts_pattern.split(':') | replace('tag_conga_variants_','') }}"

- include_tasks: "inventory_ec2.yml"
  when: "'ec2' in group_names" # aws inventory is used

- include_tasks: "inventory_default.yml"
  when: "'ec2' not in group_names" # 'default' static inventory is used

- name: "Ensure that host pattern is only for one variant when multiple nodes exist on one machine"
  assert:
    that:
      - _host_pattern_variants | length == 1
    msg:
      - "Use only one variant in the host pattern when setting up a singlehost instance!"
      - "Found conga_nodes on instance: {{ _instance_conga_nodes | join(', ') }}"
      - "Host pattern variants: {{ _host_pattern_variants | join(', ') }}"
  when: _instance_conga_nodes | length > 1

- name: "Set instance_conga_variant_node_mapping"
  set_fact:
    _instance_conga_variant_node_mapping: "{{ _instance_conga_variant_node_mapping | combine({ item.split('=')[0] : item.split('=')[1] }) }}"
  with_items: "{{ _instance_conga_variant_node_mapping_list }}"
  when: _instance_conga_variant_node_mapping_list | length > 0

- name: "set conga_node (one node on host)"
  set_fact:
    conga_node: "{{ _instance_conga_nodes[0] }}"
  when: _instance_conga_nodes | length == 1

- name: "set conga_node (multiple nodes on one host)"
  set_fact:
    conga_node: "{{ _instance_conga_variant_node_mapping[_host_pattern_variants[0]] }}"
  when: _host_pattern_variants | length == 1

- name: "Log found conga_node"
  debug:
    msg: "detected conga_node for {{ inventory_hostname }} : {{ conga_node }}"
