---
- name: Set host_pattern facts.
  host_pattern_util:
    pattern: "{{ conga_host_facts_pattern }}"
    fact_name: "_host_pattern_variants"

- name: "Debug _host_pattern_variants"
  debug:
    msg: "{{ _host_pattern_variants }}"

- name: "Use inventory_ec2."
  include_tasks: "inventory_ec2.yml"
  when: "'ec2' in group_names"  # aws inventory is used

- name: "Use inventory_openstack."
  include_tasks: "inventory_openstack.yml"
  when: "'openstack' in group_names"  # openstack inventory is used

- name: "Use inventory_default."
  include_tasks: "inventory_default.yml"
  when:
    - "'ec2' not in group_names"  # 'default' static inventory is used
    - "'openstack' not in group_names"  # 'default' static inventory is used

- name: "Ensure that _host_pattern_variants is a list"
  assert:
    that:
      - _host_pattern_variants | type_debug == 'list'
    msg: "host_pattern_variants is not a list (actual type: {{ _host_pattern_variants | type_debug }})"

- name: "Ensure that host pattern is only for one variant when multiple nodes exist on one machine."
  assert:
    that:
      - _host_pattern_variants | length == 1
    msg: >
      Use only one variant in the host pattern when setting up a singlehost instance!
      Found conga_nodes on instance: {{ _instance_conga_nodes | join(', ') }}
      Host pattern variants: {{ _host_pattern_variants | join(', ') }}
  when: _instance_conga_nodes | length > 1

- name: "Set instance_conga_variant_node_mapping."
  conga_variant_node_mapping_util:
    mappings: "{{ _instance_conga_variant_node_mapping_list }}"
    fact_name: "_instance_conga_variant_node_mapping"
  when: _instance_conga_variant_node_mapping_list | length > 0

- name: "_instance_conga_variant_node_mapping_list"
  debug:
    var: _instance_conga_variant_node_mapping_list

- name: "_instance_conga_variant_node_mapping2"
  debug:
    var: _instance_conga_variant_node_mapping

- name: "set conga_node (one node on host)."
  set_fact:
    conga_node: "{{ _instance_conga_nodes[0] }}"
  when: _instance_conga_nodes | length == 1

- name: "multiple nodes on one host."
  block:
    - name: "Ensure that conga_variant node_mapping contains the found host_pattern variant"
      assert:
        that:
          - _instance_conga_variant_node_mapping[_host_pattern_variants[0]] is defined
        msg: >
          Unable to retrieve the conga_node for '{{ _host_pattern_variants[0] }}'
          Available nodes and their variants:
          {{ _instance_conga_variant_node_mapping }}

    - name: "set conga_node (multiple nodes on one host)."
      set_fact:
        conga_node: "{{ _instance_conga_variant_node_mapping[_host_pattern_variants[0]] }}"
  when:
    - _host_pattern_variants | length == 1
    - _instance_conga_nodes | length > 1

- name: "Log found conga_node."
  debug:
    msg:
      - "conga_node         : '{{ conga_node }}'"
      - "host pattern       : '{{ conga_host_facts_pattern }}'"
      - "inventory_hostname : '{{ inventory_hostname }}'"
    verbosity: 1
